### PR TITLE
Updated to version 4.7.8

### PR DESCRIPTION
**Pull request by anmol26s**
* upgrade to 4.7.8

## Problem
- *New update is available*

## Solution
- *Updated to version 4.7.8*

## PR Status
- [X] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [X] Can be reviewed and tested.

### CODE REVIEW

**Comment by anmol26s** [comment]
@ericgaspar 
Why we have removed the root access option?

https://github.com/YunoHost-Apps/adminer_ynh/commit/a13a66cfc7c5525cfaaf096017188c81ae2d50fa#diff-6233345de4867c7ccf72bac1fc1067988d2a4c8e1ab9a746956eafccf88cfed2L90-L94

**Comment by anmol26s** [comment]
!testme

**Comment by ericgaspar** [comment]
@anmol26s I have no clues :s ... I can't remember. If you think it's missing, we should put it back I guess

**Comment by anmol26s** [comment]
!testme

**Comment by anmol26s** [comment]
!testme

**Pull request merged**
